### ISSUE TITLE
Errormessage

### ISSUE THREAD

**Issue by LarsEjaas** [jdhoek/inkscape-isometric-projection#5]
I have tried installing the extension on a win64 PC. However I seem to get the same error message no matter what side I try to convert (top, left or right side):

Traceback (most recent call last):
  File "isometric_projection.py", line 7, in <module>
    from simpletransform import Transform
ImportError: cannot import name Transform

I am on Inkscape v. 0.92.5

**Comment by jdhoek** [comment]
With the preparation for Inkscape 1.0 the newer releases of this extension (`2.*`) only work on Inkscape 1.0-beta1 and newer. Did you use [version `1.2`](https://github.com/jdhoek/inkscape-isometric-projection/releases/tag/v1.2) of this extension? That should work on older Inkscape versions.

**Comment by LarsEjaas** [comment]
Hi jdhoek

Thanks for taking the time to help!

I had the version wrong - you are correct. I downloaded the wrong version.  However, after installing the old version - this also failed - but it just freezes Inkscape with no errors. I have installed Inkscape Beta instead - this works really well. Thanks :-)

**Comment by jdhoek** [comment]
Excellent! Glad to hear you found a working solution. Thanks for reporting this issue.
